imports:
    - { resource: parameters.yml }

services:
    threedi.pia.listener:
        class: threedi\pia\event\listener
        arguments:
            - '@config'
            - '@user'
            - '@threedi.pia.pia'

        tags:
            - { name: event.listener }

    threedi.pia.pia:
        class: threedi\pia\lite\pia
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '%threedi.pia.tables.pia_table%'
